# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm-router" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "fbed17edd3d0518e91900411fe33479b2453db1fad83f2e42280061133e55b37"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a22df3ba54eb7547e934cbd60883ad3a0c1290195bde775bb4e0742420b89157"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "058adae0b101c684e12b448209d64219bca512a17c92c563bd18998a5a9ed9f8"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "74098bea90b648bed1b0b6481f9b1e045313b41e6e353120eca1cc1a3ae4f521"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llm-router"
  desc "OpenAI-compatible LLM router — one front door for Amazon Bedrock, LM Studio, and other OpenAI-compatible backends"
  homepage "https://github.com/erewhon/llm-router-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm-router"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llm-router"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    A sample multi-backend config ships in the release archive as
    configs/models.example.yaml. Quick start:

      mkdir -p ~/.config/llm-router
      curl -fsSL https://raw.githubusercontent.com/erewhon/llm-router-go/main/configs/models.example.yaml \
        -o ~/.config/llm-router/models.yaml
      llm-router -models-yaml ~/.config/llm-router/models.yaml -addr :4010

    For Amazon Bedrock, export a Bedrock API key first:
      export AWS_BEARER_TOKEN_BEDROCK="<your key>"
  EOS
end
