# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm-router" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "759cf26a5e676ef1db86e69b5fce6eab0b9096dc78e0ef338e17f81837a55ac7"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3bf102ffe80257c8068694a02d2ae6b60872fd46d7b2881a26bb349b72b7d2bf"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0635c8fd554a0f9152ec99baa8bbc74f7bca556ac07a7b9a2a110dab0dd4c2f4"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "110613cfff44975e1ee98c753dfc994f66379d1277e8b02f417d0633383b2b0b"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llm-router"
  desc "OpenAI-compatible LLM router — one front door for Amazon Bedrock, LM Studio, and other OpenAI-compatible backends"
  homepage "https://github.com/erewhon/llm-router-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm-router"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llm-router"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    A sample multi-backend config ships in the release archive as
    configs/models.example.yaml. Quick start:

      mkdir -p ~/.config/llm-router
      curl -fsSL https://raw.githubusercontent.com/erewhon/llm-router-go/main/configs/models.example.yaml \
        -o ~/.config/llm-router/models.yaml
      llm-router -models-yaml ~/.config/llm-router/models.yaml -addr :4010

    For Amazon Bedrock, export a Bedrock API key first:
      export AWS_BEARER_TOKEN_BEDROCK="<your key>"
  EOS
end
