# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm-router" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3ca4b1961da4e50a08e1e2eb8f1a234e8c060beae2138fd40975aab4ead1b8ae"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "966c5a9ecee5d52f56124447ff9e086c015bd22f04f148e14d6ea5fb392aa4c7"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ecbf340535c75b39356e7fa2917e915ad12a7dd68e183992c929960033c74bca"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "465ad303bcea546912a129bfe5e30ee6b472eab29e1ea6a873480f2aa2a46cd4"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/llm-router_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llm-router"
  desc "OpenAI-compatible LLM router — one front door for Amazon Bedrock, LM Studio, and other OpenAI-compatible backends"
  homepage "https://github.com/erewhon/llm-router-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm-router"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llm-router"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    A sample multi-backend config ships in the release archive as
    configs/models.example.yaml. Quick start:

      mkdir -p ~/.config/llm-router
      curl -fsSL https://raw.githubusercontent.com/erewhon/llm-router-go/main/configs/models.example.yaml \
        -o ~/.config/llm-router/models.yaml
      llm-router -models-yaml ~/.config/llm-router/models.yaml -addr :4010

    For Amazon Bedrock, export a Bedrock API key first:
      export AWS_BEARER_TOKEN_BEDROCK="<your key>"
  EOS
end
