# This file was generated by GoReleaser. DO NOT EDIT.
cask "orpheus-say" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "ef6644128a5f1f5776f725593205cffe460d67db68b778674f745bb48ea2c78b"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df3a0ce281fb11eb9657151bcbf814910c45541bd7c2d4f76934d826952168d7"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6289605bc060ebd12326a17ea1148f962fc996cbc3e6a730140c36d04241ecf1"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29bf647cfe77751d85e62715ebb1a94f523676718750acac6005e11aea2af597"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orpheus-say"
  desc "Command-line Orpheus text-to-speech: speak text via an OpenAI /v1/audio/speech endpoint and play it on the default audio output"
  homepage "https://github.com/erewhon/llm-router-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orpheus-say"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orpheus-say"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    orpheus-say speaks text via an Orpheus /v1/audio/speech endpoint and plays
    it on your default audio output (macOS: afplay; Linux: paplay/ffplay/aplay).

    Point it at your Orpheus server, then talk:
      export ORPHEUS_URL=http://<host>:5397   # or a local mlx-audio server
      orpheus-say "Hello there"
      echo "piped text works too" | orpheus-say
  EOS
end
