# This file was generated by GoReleaser. DO NOT EDIT.
cask "orpheus-say" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "ee53f7d09047e3b150f97d65c6d6d1f0b88c2f7dca72525ce851e7aaa320cbee"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01b40693b669e1b4139324eb60ac048b94180530602e1eb80d40feaf345f75a5"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8cc065c8c68eb2c6146db42287339b0d74c7eeee3c2a9b50c60bc3be47f2f17c"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e74ba83d535aa517fa9bb039ce865e71a0f1fcdaeaafff029e5e97397573f309"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orpheus-say"
  desc "Command-line Orpheus text-to-speech: speak text via an OpenAI /v1/audio/speech endpoint and play it on the default audio output"
  homepage "https://github.com/erewhon/llm-router-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orpheus-say"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orpheus-say"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    orpheus-say speaks text via an Orpheus /v1/audio/speech endpoint and plays
    it on your default audio output (macOS: afplay; Linux: paplay/ffplay/aplay).

    Point it at your Orpheus server, then talk:
      export ORPHEUS_URL=http://<host>:5397   # or a local mlx-audio server
      orpheus-say "Hello there"
      echo "piped text works too" | orpheus-say
  EOS
end
