# This file was generated by GoReleaser. DO NOT EDIT.
cask "orpheus-say" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "9e97f3a8b75151b175fcab8da47bcf9fd94df56d151ab683c852f087859d9d05"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "43a16aa7342ac70fcdc87a30917027d0f17b6093925985320cfd43cd45651284"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c77275d2de19ada0f5c2220368cddb8bc8e7cbe12d31af301571f6f6fdd33310"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c98cab7d8c2f6228dadbd797ac003fe80357fa2dfa29cb781ea3e90de384c11"
      url "https://github.com/erewhon/llm-router-go/releases/download/v#{version}/orpheus-say_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orpheus-say"
  desc "Command-line Orpheus text-to-speech: speak text via an OpenAI /v1/audio/speech endpoint and play it on the default audio output"
  homepage "https://github.com/erewhon/llm-router-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orpheus-say"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orpheus-say"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    orpheus-say speaks text via an Orpheus /v1/audio/speech endpoint and plays
    it on your default audio output (macOS: afplay; Linux: paplay/ffplay/aplay).

    Point it at your Orpheus server, then talk:
      export ORPHEUS_URL=http://<host>:5397   # or a local mlx-audio server
      orpheus-say "Hello there"
      echo "piped text works too" | orpheus-say
  EOS
end
