# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenator" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9bd153862d710f0bc8aee02839da82f6388da8fc77003dbe6084fb07d9e27dfa"
      url "https://github.com/erewhon/tokenator/releases/download/v#{version}/tokenator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd97443701391000cc5905fa642e85d37352f214510ef3a26d0ad136ffc96406"
      url "https://github.com/erewhon/tokenator/releases/download/v#{version}/tokenator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc6d8f7eb441603b5e9b9baa91843173bbe1c26c85ca5fb665170d9adb48dbe1"
      url "https://github.com/erewhon/tokenator/releases/download/v#{version}/tokenator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de3f55f2a5381797448ac1f5ed5f41c22f4cc9c5851fee21a64181e799856a01"
      url "https://github.com/erewhon/tokenator/releases/download/v#{version}/tokenator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tokenator"
  desc "Token and prompt-cache profiler for AI coding agents (Claude Code, OpenCode): usage reports, cache doctor, session browser, A/B bench harness"
  homepage "https://github.com/erewhon/tokenator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenator"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Quick start:
      tokenator ingest    # profile your Claude Code / OpenCode transcripts
      tokenator report    # usage rollups with cache splits
      tokenator serve     # session browser web UI on 127.0.0.1:8990

    The database lives at ~/.local/share/tokenator/tokenator.db and stores
    sizes/hashes only — never transcript content.
  EOS
end
