# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentMonitor < Formula
  desc "TUI for tracking Claude Code agents in tmux sessions"
  homepage "https://github.com/erewhon/agent-monitor"
  version "0.9.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/erewhon/agent-monitor/releases/download/v0.9.2/agent-monitor_darwin_arm64.tar.gz"
      sha256 "12a4adf441b9448342866c0f027f4e71e58128630a2f72df256a175905fae7cb"

      def install
        bin.install "agent-monitor"
        bin.install "agent-monitor-session"
        bin.install "focus-agent-monitor"
        bin.install "agent-monitor-placeholder"
        (etc/"agent-monitor").install "tmux-outer.conf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/agent-monitor/releases/download/v0.9.2/agent-monitor_linux_amd64.tar.gz"
      sha256 "5da3470926fc1273a61d07157ec5c7df02f341164d6f3a4e3105addcd3f8d3a8"
      def install
        bin.install "agent-monitor"
        bin.install "agent-monitor-session"
        bin.install "focus-agent-monitor"
        bin.install "agent-monitor-placeholder"
        (etc/"agent-monitor").install "tmux-outer.conf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/agent-monitor/releases/download/v0.9.2/agent-monitor_linux_arm64.tar.gz"
      sha256 "86763748aeaf8f2d5ecf4b75b03d740d3b06c35fe2d6902b2533c9cb3f840fc4"
      def install
        bin.install "agent-monitor"
        bin.install "agent-monitor-session"
        bin.install "focus-agent-monitor"
        bin.install "agent-monitor-placeholder"
        (etc/"agent-monitor").install "tmux-outer.conf"
      end
    end
  end

  def caveats
    <<~EOS
      The tmux config has been installed to:
        #{etc}/agent-monitor/tmux-outer.conf

      To use the session launcher, you may want to update the config path
      in agent-monitor-session or copy it to ~/.config/agent-monitor-tmux.conf
    EOS
  end

  test do
    assert_match "agent-monitor", shell_output("#{bin}/agent-monitor --help 2>&1", 1)
  end
end
