# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentMonitor < Formula
  desc "TUI for tracking Claude Code agents in tmux sessions"
  homepage "https://github.com/erewhon/agent-monitor"
  version "0.10.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/erewhon/agent-monitor/releases/download/v0.10.2/agent-monitor_darwin_arm64.tar.gz"
      sha256 "4cd7df873a34e319cd7200fd235fb0f17f2cd915c8404aacb22173f96379537d"

      def install
        bin.install "agent-monitor"
        bin.install "agent-monitor-session"
        bin.install "focus-agent-monitor"
        bin.install "agent-monitor-placeholder"
        (etc/"agent-monitor").install "tmux-outer.conf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/agent-monitor/releases/download/v0.10.2/agent-monitor_linux_amd64.tar.gz"
      sha256 "1a94a36e652fb6a7ab7bf671220d86d8b8127f0b71e6019289abb004b1111e89"
      def install
        bin.install "agent-monitor"
        bin.install "agent-monitor-session"
        bin.install "focus-agent-monitor"
        bin.install "agent-monitor-placeholder"
        (etc/"agent-monitor").install "tmux-outer.conf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/agent-monitor/releases/download/v0.10.2/agent-monitor_linux_arm64.tar.gz"
      sha256 "27781af332d25ea73c5bc878ec1a6e2f7e926e9d4d3490d1f7090adb863b1204"
      def install
        bin.install "agent-monitor"
        bin.install "agent-monitor-session"
        bin.install "focus-agent-monitor"
        bin.install "agent-monitor-placeholder"
        (etc/"agent-monitor").install "tmux-outer.conf"
      end
    end
  end

  def caveats
    <<~EOS
      The tmux config has been installed to:
        #{etc}/agent-monitor/tmux-outer.conf

      To use the session launcher, you may want to update the config path
      in agent-monitor-session or copy it to ~/.config/agent-monitor-tmux.conf
    EOS
  end

  test do
    assert_match "agent-monitor", shell_output("#{bin}/agent-monitor --help 2>&1", 1)
  end
end
