# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pitf < Formula
  desc "One command over the smithy LLM tools: agent-monitor, tokenator, llm-router, benchmarks"
  homepage "https://github.com/erewhon/pitf"
  version "0.1.11"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.11/pitf_0.1.11_darwin_amd64.tar.gz"
      sha256 "0a160c4b1b8e856fbd5e58868b7a3e4cd0c72276bafc3e3aa4b8066bc24a7967"

      define_method(:install) do
        bin.install "pitf"
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.11/pitf_0.1.11_darwin_arm64.tar.gz"
      sha256 "326996eec5564b287dde5e1dc13d7cc1a9c7dfd401e3c685ddf9650272cca66b"

      define_method(:install) do
        bin.install "pitf"
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.11/pitf_0.1.11_linux_amd64.tar.gz"
      sha256 "22bd568cb886b2b2ecd318ef71899790a777cb3593bee15e9284aa81eb8eadde"
      define_method(:install) do
        bin.install "pitf"
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.11/pitf_0.1.11_linux_arm64.tar.gz"
      sha256 "df0c82304d0a0e123f9ae8f042937c61ce2cbf7dfff3e996de3650a7d6c6ed85"
      define_method(:install) do
        bin.install "pitf"
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Built in: pitf monitor | tokens | router … | bench sweep | session | model | dashboard | config
      Python tools (need uv + the checkouts under ~/code/smithy or PITF_SMITHY_DIR): pitf qual | forge | meta

      First run: pitf config init, then pitf doctor
    EOS
  end
end
