# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pitf < Formula
  desc "One command over the smithy LLM tools: agent-monitor, tokenator, llm-router, benchmarks"
  homepage "https://github.com/erewhon/pitf"
  version "0.1.2"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.2/pitf_0.1.2_darwin_amd64.tar.gz"
      sha256 "5c362df7ddae03e53597262e26efa641f252a60cd0427a0a68e078ed5afa4999"

      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.2/pitf_0.1.2_darwin_arm64.tar.gz"
      sha256 "07874a7ee28e1fdbeb0f58377f0204fd4da0a5e41814a0459f59a612ffbf92f9"

      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.2/pitf_0.1.2_linux_amd64.tar.gz"
      sha256 "4295df3815bb9ea4381d9bb5a7158320d799e335ffb4dc2044e8b3fea40703fc"
      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.2/pitf_0.1.2_linux_arm64.tar.gz"
      sha256 "17f9df272ad36dcc1572cf8aa32f95e7580c9eb3252250b605a90f77e47fb42e"
      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Built in: pitf monitor | tokens | router … | bench sweep | session | model | config
      External (need uv + the Python checkouts on PITF_SMITHY_DIR): pitf qual | forge | meta | bench-py

      First run: pitf config init
    EOS
  end
end
