# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pitf < Formula
  desc "One command over the smithy LLM tools: agent-monitor, tokenator, llm-router, benchmarks"
  homepage "https://github.com/erewhon/pitf"
  version "0.1.3"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.3/pitf_0.1.3_darwin_amd64.tar.gz"
      sha256 "e2aa14119c88ccf53b8ff5f52b2d22f407d4f040194ce7efc9bf076aa6d6953b"

      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.3/pitf_0.1.3_darwin_arm64.tar.gz"
      sha256 "fe94ba710706c284671c3fbdac4655b0c9ad932e1ab6e80ad8e32ee516818170"

      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.3/pitf_0.1.3_linux_amd64.tar.gz"
      sha256 "ee2239168eb28ebc5fd31f966b09d2ba92d7cada39fce4ea2abf4e62901330a4"
      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erewhon/pitf/releases/download/v0.1.3/pitf_0.1.3_linux_arm64.tar.gz"
      sha256 "630cfc20ddd5b4989ce54b969c7bfaa85e00a16e03dcbf50f1c65c53aac78a70"
      define_method(:install) do
        bin.install "pitf"
        # The Python-tool shims: pitf qual / forge / meta / bench-py. They need
        # uv and the checkouts under ~/code/smithy (or PITF_SMITHY_DIR).
        bin.install Dir["contrib/wrappers/pitf-*"]
        generate_completions_from_executable(bin/"pitf", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Built in: pitf monitor | tokens | router … | bench sweep | session | model | config
      External (need uv + the Python checkouts on PITF_SMITHY_DIR): pitf qual | forge | meta | bench-py

      First run: pitf config init
    EOS
  end
end
